# Generated by Django 3.2.8 on 2021-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_auto_20211031_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='profile_pics/', blank=True, default='profile_pics/default.jpg')
        ),
    ]
