# Generated by Django 3.2.8 on 2021-10-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0005_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'My Post', 'verbose_name_plural': 'Post'},
        ),
    ]
