# Generated by Django 3.2.8 on 2021-10-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0006_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighborhood',
            new_name='neighbourhood',
        ),
    ]
