# Generated by Django 3.2.8 on 2021-11-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0007_rename_neighborhood_business_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
